### ISSUE TITLE
`skip` flag not working field custom types mapping

### ISSUE THREAD

**Issue by bcordobaq** [parvez3019/go-swagger3#15]
Hi, I realized that go-swagger3 still continues with the type mapping for those fields marked with `skip: "true"`.
For example:

``` go
type Foo struct {
  field1 string `json:"field1"`
  field2 string `json:"field2"`
  field3 Bar `json:"field3" skip:"true"`
}

type Bar struct {
  ...
}
```

And, if I don't want to map the `Bar` type, it also processes it.

**Comment by parvez3019** [comment]
@gocodify do you want to take a look at this one?

**Comment by qequ** [comment]
For more clarification, this bug only affects custom types made by user. In the case of the example made by @bcordobaq 
the tool will generate inside schemas' component section an element Bar that is not used anywhere else

```

"components": {
    "schemas": {
         ...
       pkg.path....Bar: {
           ...
        }
    }
}
```

Possibly need to check the process of creating components and ensure the custom types are used
