### ISSUE TITLE
Parsing go.mod that contains a replace directive for external module forks

### ISSUE THREAD

**Issue by dcs3spp** [parvez3019/go-swagger3#21]
Hi,

I am trying to learn go-swagger3 and so far have managed to get a working demo setup. I am now trying it on a larger codebase which contains a fork to an external repository. Subsequently, the `go.mod` file uses the replace directive, e.g. something similar to:

**g.mod file**
```go
// last line of go.mod file uses replace directive for fork of external module
replace example.io/goexample => github.com/example.org/goexample v1.20.7
```

When I issue the command from the project root folder:

```bash
go-swagger3 --debug --module-path . --output oas.yml --schema-without-pkg --generate-yaml true
```

Parsing of the go.mod fails with error:

```bash
INFO[0000] Parsing Initialized
INFO[0000] Parsing Info ...
INFO[0000] Parsing Modules ...
INFO[0000] Parsing GoMod Info ...
2023/04/28 15:51:48 Error: expect package version, got "=>"
```

If I remove the replace directive in the *go.mod* file the _oas.yml_ file is generated successfully by go-swagger3.

Will there be future support for parsing the replace directive for projects that use forks of external modules?

**Comment by qequ** [comment]
Thanks for the report  @dcs3spp 
Could you add a go.mod example that contains a replace directive?

**Comment by dcs3spp** [comment]
Hi @qequ 

Some example of _go.mod_ containing replace directives can be found in [traefik](https://github.com/traefik/traefik/blob/master/go.mod) and [tyk](https://github.com/TykTechnologies/tyk/blob/master/go.mod)

**Comment by qequ** [comment]
Checking on the code it seems that we're using an old , no longer mantained, parser for go mod files ( https://github.com/mikunalpha/go-module ). I'm gonna work on this updating that parser
