### ISSUE TITLE
How to mark field as nullable?

### ISSUE THREAD

**Issue by jrozbicki** [parvez3019/go-swagger3#26]
I would like to mark `Name` as `nullable` field. How can I achieve that?

```
type Task struct {
	ID        int            `json:"task_id" gorm:"index:idx_name,unique" required:"true"`
	Name      string         `json:"task_name"  required:"true"`
}
```

I've tried `nullable: true`, `x-nullable: true` without much success. Returned json doesn't return anything that would resemble nullability.

**Comment by parvez3019** [comment]
Hey @jrozbicki Unfortunately this hasn't been implemented yet.
Ref -  https://github.com/parvez3019/go-swagger3/blob/cc38ece16a6731e11876b5091e8e8bb0531d2887/openApi3Schema/oas.go#L165
