### ISSUE TITLE
 Can this project use generic types in Swagger?

### ISSUE THREAD

**Issue by TheRiseOfDavid** [parvez3019/go-swagger3#49]
Hello,

This is my first time using this project. Previously, I used go-swagger, but now I prefer to use OpenAPI 3.0.

After studying the README, I'm not sure if generic classes are supported. Could you please confirm whether this project can handle generic types in Swagger?

Thank you for your assistance.

**Comment by parvez3019** [comment]
Hi @TheRiseOfDavid Generics are not supported at the moment.

**Comment by TheRiseOfDavid** [comment]
@parvez3019  Thank your answer.
