### ISSUE TITLE
Custom type objects are generated twice in Components 

### ISSUE THREAD

**Issue by qequ** [parvez3019/go-swagger3#5]
@parvez3019 when custom type objects are generated in Components two exact equal objects are generated,one with the name of the custom type alone and another with the name plus the package. 

e.g. in the integration_test's expected.json there is a CreateUserRequest (among other custom types) which appears twice in Components;  `CreateUserRequest` and `github.com.parvez3019.go-swagger3.model.CreateUserRequest`. The $Ref points to `github.com.parvez3019.go-swagger3.model.CreateUserRequest` and the other is never used.

Why is this? Shouldn't there be only one of the the objects?

**Comment by parvez3019** [comment]
@qequ yes you are correct, Ideally, we should have one of the schema objects only.

I had to do this duplication a while back as a quick fix for some other issue related to reference objects.
Please allow me some time, I'll take a relook at the issue and try to fix it.

**Comment by parvez3019** [comment]
@qequ there is one cli arg flag `schema-without-pkg` which is set false in the test setup hence there are duplicated schemas are getting generated, we can update the test setup and run it with true setting and it will remove the duplication?

**Comment by qequ** [comment]
> there is one cli arg flag schema-without-pkg which is set false in the test setup hence there are duplicated schemas are getting generated

This is exactly the bug

**Comment by qequ** [comment]
The thing is, it's not a test issue; it's an implementation issue. I'm not sure how  `schema-without-pkg` flag works but it seems that when it's set to true, generates the Components objects without the pkg names and the $Refs use those names, but when it's set to false it generates the objects without the pkg names anyway and also generates the objects with the pkg names and those are the objects that are used for the $Refs.

I think that when set to false it should only generate the Components objects with the pkg.

Changing the tests will hide the problem, but it will continue being there any time a user has custom types
